from typing import Optional

from pydantic import Field

from state_models.common_models import ExtractedInformation
from state_models.common_state import CorrectiveRAGState


class LaborStandardsState(CorrectiveRAGState):
    """
    State model for Labor Standards Information retrieval and response generation.
    Inherits base Corrective RAG state and adds additional fields specific to this workflow.
    """

    rewritten_question: str = Field(
        default="",
        description="The rewritten version of the user's original question, if applicable.",
    )
    extracted_info: Optional[ExtractedInformation] = Field(
        default=None,
        description="The structured information extracted from the knowledge base relevant to the question.",
    )
    final_answer: Optional[str] = Field(
        default=None,
        description="The response generated by the node model based on retrieved documents.",
    )
