from .gender_prompts import ANSWER_PROMPT as GENDER_ANSWER_PROMPT
from .gender_prompts import EXTRACTION_PROMPT as GENDER_EXTRACTION_PROMPT
from .gender_prompts import REWRITE_PROMPT as GENDER_REWRITE_PROMPT
from .insurance_prompts import ANSWER_PROMPT as INSURANCE_ANSWER_PROMPT
from .insurance_prompts import EXTRACTION_PROMPT as INSURANCE_EXTRACTION_PROMPT
from .insurance_prompts import REWRITE_PROMPT as INSURANCE_REWRITE_PROMPT
from .labor_prompts import ANSWER_PROMPT as LABOR_ANSWER_PROMPT
from .labor_prompts import EXTRACTION_PROMPT as LABOR_EXTRACTION_PROMPT
from .labor_prompts import REWRITE_PROMPT as LABOR_REWRITE_PROMPT

__all__ = [
    "INSURANCE_EXTRACTION_PROMPT",
    "INSURANCE_REWRITE_PROMPT",
    "INSURANCE_ANSWER_PROMPT",
    "LABOR_EXTRACTION_PROMPT",
    "LABOR_REWRITE_PROMPT",
    "LABOR_ANSWER_PROMPT",
    "GENDER_EXTRACTION_PROMPT",
    "GENDER_REWRITE_PROMPT",
    "GENDER_ANSWER_PROMPT",
]
